config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get "users/show" => "users#show"
  get "/search", to: "searches#search"
  get "/keyword_search", to: "searches#keyword_search"
  get "/reservations/confirm", to: "reservations#confirm"
  get "/reservations/:id/edit_confirm", to: "reservations#edit_confirm"
  root to: "searches#top"
  resources :rooms
  resources :reservations, only: [:index, :new, :confirm, :create, :show, :edit, :destroy, :update] do
    collection do
      post :confirm
    end
    member do
      patch :edit_confirm
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_partial.html.erb
<div class="partial">
  <header>
    <% if user_signed_in? %>
      <h4>
        <%= link_to "宿泊施設検索サイト", root_path %>
      </h4>
      <div class="dropdown">
        <ul class="menu-list">
          <div class="menu-item">
           <% if @user.avatar.present? %>
             <img src=<%= @user.avatar %> class = "icon_image">
           <% else %>
             <img src="/assets/default-user-icon.png" class = "icon_image">
           <% end %>
          </div>
          <li class="menu-item drop-menu">
            <input type="checkbox" id="submenu-toggle-2">
            <label for="submenu-toggle-2"><%= current_user.name %></label>
            <ul class="submenu">
             <li class="submenu-item"><%= link_to "施設の新規登録", new_room_path %></li>
             <li class="submenu-item"><%= link_to "予約済み一覧", reservations_path %></li>
             <li class="submenu-item"><%= link_to "登録済み一覧", rooms_path %></li>
             <li class="submenu-item"><%= link_to "アカウント設定", users_show_path %></li>
             <li class="submenu-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <ul/>
          </li>
        </ul>
      </div>
    <% else %>
      <h4>
        <%= link_to "宿泊施設検索サイト", root_path %>
      </h4>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </header>
  <%= yield %>
</div>

app/views/shared/_reservation.html.erb
<% if user_signed_in? %>
  <h2>部屋を予約する</h2>
  <%= form_with(url:confirm_reservations_path, method: :get) do |f| %>
    <table>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <tr>
        <th><%= f.label :checkin ,"チェックイン日" %></th>
        <td><%= f.date_field :checkin %></td>
      </tr>

      <tr>
        <th><%= f.label :checkout ,"チェックアウト日" %></th>
        <td><%= f.date_field :checkout %></td>
      </tr>

      <tr>
        <th><%= f.label :person ,"人数" %></th>
        <td><%= f.text_field :person %></td>
      </tr>
    </table>

    <% if flash[:notice_no_create] %>
      <p class="notice"><%= flash[:notice_no_create] %></p>
    <% end %>
    <div>
      <ul>
        <li><%= f.submit "予約する"%></li>
      </ul>
    </div>
  <% end %>
<% else %>
  <%= link_to "ログイン", new_user_session_path %> 
<% end %>

app/views/shared/_setting.html.erb
<div class="setting">
<h1>設定</h1>
<%= link_to "プロフィール", profile_path(current_user.id) %>
<%= link_to "アカウント", users_show_path %>
</div>