config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get "users/show" => "users#show"
  get "/search", to: "searches#search"
  get "/keyword_search", to: "searches#keyword_search"
  get "/reservations/confirm", to: "reservations#confirm"
  get "/reservations/:id/edit_confirm", to: "reservations#edit_confirm"
  root to: "searches#top"
  resources :rooms
  resources :reservations, only: [:index, :new, :confirm, :create, :show, :edit, :destroy, :update] do
    collection do
      post :confirm
    end
    member do
      patch :edit_confirm
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :checkin, presence: true
  validates :checkout, presence: true
  validates :person, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validate :date_before_start
  validate :start_end_check
  belongs_to :user
  belongs_to :room
end

def date_before_start
  return if checkin.blank?
  errors.add(:checkin, "は今日以降のものを選択してください") if checkin < Date.today
end

def start_end_check
  if checkin != nil && checkout != nil
    errors.add(:checkout, ": 開始日以前の日付は使用できません")
  unless
    checkout > checkin
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = Reservation.where(user_id: current_user.id)
    @rooms = Room.all
    @user = current_user
  end

  def new
    @reservation = Reservation.new
    @user = current_user
    @room = Room.new
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @room = Room.where(id: @reservation.room_id)
    if @reservation.invalid?
      flash[:notice_no_create] = "バリデーションエラーがあります"
      redirect_to controller: :rooms, action: :show, id: @reservation.room_id
    else
      @reservation.many_days = (@reservation.checkout - @reservation.checkin)
      @reservation.total_price = @reservation.room.room_price * @reservation.person * @reservation.many_days
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @room = Room.where(id: @reservation.room_id)
    if @reservation.save
      flash[:notice_create] = "予約情報を登録しました"
      redirect_to :reservations
    else
      flash[:notice_no_create] = "予約情報の登録に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @user = current_user
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @user = current_user
    @room = Room.where(id: @reservation.room_id)
    if @reservation.user_id != current_user.id
      redirect_to root_path
    end
  end

  def edit_confirm
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @room = Room.where(id: @reservation.room_id)
    if @reservation.invalid?
      flash[:notice_no_create] = "バリデーションエラーがあります"
      redirect_to controller: :rooms, action: :show, id: @reservation.room_id
    else
      @reservation.many_days = (@reservation.checkout - @reservation.checkin)
      @reservation.total_price = @reservation.room.room_price * @reservation.person * @reservation.many_days
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    @user = current_user
    if @reservation.update(reservation_params)
      flash[:notice_update] = "予約情報を更新しました"
      redirect_to :reservations
    else
      flash[:notice_no_update] = "予約情報を更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice_destroy] = "予約情報を削除しました"
    redirect_to :reservations
  end

  private

  def reservation_params
    params.permit(:checkin, :checkout, :person, :room_price, :total_price, :user_id, :room_id)
  end
end

app/views/reservations/confirm.html.erb
<%= render "shared/partial" %>

<h3>予約内容の確認</h3>

<% if @room.find(@reservation.room_id).room_image.present? %>
  <img src=<%= @room.find(@reservation.room_id).room_image %> class = "room_image">
<% else %>
  <img src="/assets/default-room_image-icon.png" class = "room_image">
<% end %>
<%= form_with(url:reservations_path, method: :post) do |f| %>
  <table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン日" %></th>
      <td><%= l @reservation.checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkin ,"チェックアウト日" %></th>
      <td><%= l @reservation.checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :many_days ,"宿泊日数" %></th>
      <td><%= @reservation.many_days %>日</td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= @reservation.person %>名</td>
    </tr>

    <tr>
      <th><%= f.label :total_price ,"合計金額" %></th>
      <td>¥<%= @reservation.total_price %></td>
    </tr>

  </table>

  <%= f.hidden_field :checkin ,value: @reservation.checkin %>
  <%= f.hidden_field :checkout ,value: @reservation.checkout %>
  <%= f.hidden_field :person ,value: @reservation.person %>
  <%= f.hidden_field :many_days ,value: @reservation.many_days %>
  <%= f.hidden_field :total_price ,value: @reservation.total_price %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :room_id, value: @reservation.room_id %>
 <% if flash[:notice_no_create] %>
   <p class="notice"><%= flash[:notice_no_create] %></p>
 <% end %>

  <div>
    <ul>
      <li><%= f.submit "予約" %></li>
      <li><%= link_to "キャンセル", :reservations %></li>
    </ul>
  </div>

  <%= render "shared/error", obj: @reservation %> 
<% end %>

app/views/reservations/edit.html.erb
<%= render "shared/partial" %>

<h3>再予約</h3>

<% if @room.find(@reservation.room_id).room_image.present? %>
  <img src=<%= @room.find(@reservation.room_id).room_image %> class = "room_image">
<% else %>
  <img src="/assets/default-room_image-icon.png" class = "room_image">
<% end %>

<%= form_with(url:edit_confirm_reservation_path(@reservation), method: :get) do |f| %>
  <table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン日" %></th>
      <td><%= f.date_field :checkin, value: @reservation.checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkout ,"チェックアウト日" %></th>
      <td><%= f.date_field :checkout, value: @reservation.checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= f.text_field :person, value: @reservation.person %></td>
    </tr>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :room_id, value: @reservation.room_id %>
  </table>
  <% if flash[:notice_no_create] %>
    <p class="notice"><%= flash[:notice_no_create] %></p>
  <% end %>
  <div>
    <ul>
      <li><%= f.submit "再予約"%></li>
      <li><%= link_to "キャンセル", :reservations %></li>
    </ul>
  </div>

  <% if flash[:notice_no_update] %>
    <p class="notice"><%= flash[:notice_no_update] %></p>
  <% end %>
  <%= render "shared/error", obj: @reservation %> 
  <% end %>

app/views/reservations/edit.index.erb
<%= render "shared/partial" %>

<h3>予約の編集</h3>

<%= form_with model: @reservation do |f| %>
<table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン" %></th>
      <td><%= f.date_field :checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkout ,"チェックアウト" %></th>
      <td><%= f.date_field :checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= f.text_field :person %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "編集を完了する"%></li>
      <li><%= link_to "キャンセル", :reservations %></li>
    </ul>
  </div>

 <% if flash[:notice_no_update] %>
   <p class="notice"><%= flash[:notice_no_update] %></p>
 <% end %>
 <%= render "shared/error", obj: @reservation %> 
<% end %>

app/views/reservations/edit_confirm.html.erb
<%= render "shared/partial" %>

<h3>予約内容の確認</h3>

<% if @room.find(@reservation.room_id).room_image.present? %>
  <img src=<%= @room.find(@reservation.room_id).room_image %> class = "room_image">
<% else %>
  <img src="/assets/default-room_image-icon.png" class = "room_image">
<% end %>

<%= form_with(url:reservation_path, method: :patch) do |f| %>
   <table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン日" %></th>
      <td><%= l @reservation.checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkin ,"チェックアウト日" %></th>
      <td><%= l @reservation.checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :many_days ,"宿泊日数" %></th>
      <td><%= @reservation.many_days %>日</td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= @reservation.person %>名</td>
    </tr>

    <tr>
      <th><%= f.label :total_price ,"合計金額" %></th>
      <td>¥<%= @reservation.total_price %></td>
    </tr>
    
   </table>

   <%= f.hidden_field :checkin ,value: @reservation.checkin %>
   <%= f.hidden_field :checkout ,value: @reservation.checkout %>
   <%= f.hidden_field :person ,value: @reservation.person %>
   <%= f.hidden_field :many_days ,value: @reservation.many_days %>
   <%= f.hidden_field :total_price ,value: @reservation.total_price %>
   <%= f.hidden_field :user_id, value: @user.id %>
   <%= f.hidden_field :room_id, value: @reservation.room_id %>

   <% if flash[:notice_no_create] %>
    <p class="notice"><%= flash[:notice_no_create] %></p>
   <% end %>

   <div>
    <ul>
      <li><%= f.submit "予約" %></li>
      <li><%= link_to "キャンセル", :reservations %></li>
    </ul>
   </div>

   <%= render "shared/error", obj: @reservation %> 
<% end %>

app/views/reservations/index.html.erb
<div style="display: flex;justify-content: space-between">
<%= render "shared/partial" %>
<h3>予約済み一覧</h3>
</div>

<div>
<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>合計料金</th>
      <th>チェックイン日</th>
      <th>チェックアウト日</th>
      <th>予約確定日時</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |f| %>
      <tr>
        <td>
         <% if @rooms.find(f.room_id).room_image.present? %>
          <img src=<%= @rooms.find(f.room_id).room_image %> class = "room_image">
         <% else %>
          <img src="/assets/default-room_image-icon.png" class = "room_image">
         <% end %>
        </td>
        <td><%= link_to "#{@rooms.find(f.room_id).room_name}", @rooms.find(f.room_id) %></td>
        <td><%= @rooms.find(f.room_id).room_content %></td>
        <td><%= f.total_price %>円</td>
        <td><%= f.checkin %></td>
        <td><%= f.checkout %></td>
        <td><%= l f.updated_at, format: :time %></td>
        <td><%= link_to "再予約", [:edit, f] %></td>
        <td><%= link_to "削除", f, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 <% if flash[:notice_create] %>
   <p class="notice"><%= flash[:notice_create] %></p>
 <% end %>
 <% if flash[:notice_update] %>
   <p class="notice"><%= flash[:notice_update] %></p>
 <% end %>
 <% if flash[:notice_destroy] %>
   <p class="notice"><%= flash[:notice_destroy] %></p>
 <% end %>

</div>

app/views/reservations/new.html.erb
<%= render "shared/partial" %>
<h3>新規予約</h3>

<%= form_with model: @reservation do |f| %>
  <table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン日" %></th>
      <td><%= f.date_field :checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkout ,"チェックアウト日" %></th>
      <td><%= f.date_field :checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= f.text_field :person %></td>
    </tr>

    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :room_id, value: @room_id %>

  </table>

 <% if flash[:notice_no_create] %>
   <p class="notice"><%= flash[:notice_no_create] %></p>
 <% end %>

  <div>
    <ul>
      <li><%= f.submit "保存"%></li>
      <li><%= link_to "キャンセル", :reservations %></li>
    </ul>
  </div>

  <%= render "shared/error", obj: @reservation %> 
<% end %>

app/views/reservations/show.html.erb
<%= render "shared/partial" %>
<%= link_to '戻る', :back %>
<%= link_to "編集", edit_reservation_path(@reservation.id) %>
<%= form_with model: @reservation do |f| %>
<table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン" %></th>
      <td><%= @reservation.checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkin ,"チェックアウト" %></th>
      <td><%= @reservation.checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= @reservation.person %></td>
    </tr>
  </table>

<% end %>